server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/oragnization
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=yourVeryLongSecretKeyForJwtGeneration12345678901234567890
jwt.expiration=3000000
